[workspace]
resolver = "2"
members = ["first-crate", "second-crate", "third-crate", "trait-crate"]

[workspace.dependencies]
first-crate = { path = "first-crate" }
second-crate = { path = "second-crate" }
trait-crate = { path = "trait-crate" }
